# profiles.yml
dbt_project:
  outputs:
    dev:
      type: duckdb
      # Dynamic path configuration: Supports environment variables for Docker/CI
      # and falls back to a relative local path for development.
      path: "{{ env_var('DUCKDB_PATH', '../analytics.duckdb') }}"
      schema: main
      threads: 1
  target: dev
